[package]
name = "rsutil"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Jesse Smith <jesses2025smith@gmail.com>"]
description = "`rsutil` is a Rust library providing common utilities."
homepage = "https://github.com/jesses2025smith/rsutil"
repository = "https://github.com/jesses2025smith/rsutil"

[features]
types = []

full = ["log", "types"]

[dependencies.log]
optional = true
version = "0.4"
