name: Rust

on:
  push:
    tags:
      - "v*"
env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run debug tests
      run: >
        cargo test
        --features full
        # --verbose
    - name: Run release tests
      run: >
        cargo test
        --release
        --features full
        # --verbose
    - name: Publish
      run: >
        cargo publish
        --locked
        --token ${{ secrets.CRATES_TOKEN }}
        # --verbose

